trigger:
- main

pool:
  name: test

steps:
- script: echo Hello,World! |
  displayName: 'This is test message'
- task: Bash@3
  inputs:
     targetType: 'inline'
     script: |
       # Write your commands here
       echo 'Hello world'